export const queryKeys = {
    movies: {
        all: ['movies'] as const,
        popular: () => [...queryKeys.movies.all, 'popular'] as const,
        trending: () => [...queryKeys.movies.all, 'trending'] as const,
        upcoming: () => [...queryKeys.movies.all, 'upcoming'] as const,
        topRated: () => [...queryKeys.movies.all, 'topRated'] as const,
        nowPlaying: () => [...queryKeys.movies.all, 'nowPlaying'] as const,
        newRelease: () => [...queryKeys.movies.all, 'newRelease'] as const,
        discover: () => [...queryKeys.movies.all, 'discover'] as const,
    },
    series: {
        all: ['series'] as const,
        popular: () => [...queryKeys.series.all, 'popular'] as const,
        topRated: () => [...queryKeys.series.all, 'topRated'] as const,
        newRelease: () => [...queryKeys.series.all, 'newRelease'] as const,
        airingToday: () => [...queryKeys.series.all, 'airingToday'] as const,
        onTheAir: () => [...queryKeys.series.all, 'onTheAir'] as const,
        discover: () => [...queryKeys.series.all, 'discover'] as const,
    },
    detail: {
        all: ['detail'] as const,
        movie: (type: string, id: string) => [...queryKeys.detail.all, type, id] as const,
        credits: (type: string, id: string) => [...queryKeys.detail.all, type, id, 'credits'] as const,
        recommendations: (type: string, id: string) => [...queryKeys.detail.all, type, id, 'recommendations'] as const,
        keywords: (type: string, id: string) => [...queryKeys.detail.all, type, id, 'keywords'] as const,
        trailers: (type: string, id: string) => [...queryKeys.detail.all, type, id, 'trailers'] as const,
        reviews: (type: string, id: string) => [...queryKeys.detail.all, type, id, 'reviews'] as const,
    },
    genres: {
        all: ['genres'] as const,
        movies: () => [...queryKeys.genres.all, 'movies'] as const,
        tv: () => [...queryKeys.genres.all, 'tv'] as const,
    },
};
